# Generated by Django 4.1.7 on 2023-03-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_product_id_reviews_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
