# Generated by Django 4.1.7 on 2023-03-13 22:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reviews_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='date_created',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now),
        ),
    ]
